// angular/src/app/app.component.ts
import { Component, Inject } from '@angular/core'
import { ObservableClient } from 'src/connect/observable-client'
import { ElizaService } from 'src/gen/buf/connect/demo/eliza/v1/eliza_connectweb'
import { connectCodeFromHttpStatus} from '@bufbuild/connect-core/protocol-connect';
import { grpcWebCodeFromHttpStatus} from '@bufbuild/connect-core/protocol-grpc';

console.log(connectCodeFromHttpStatus(431));
console.log(grpcWebCodeFromHttpStatus(200));

interface Response {
    text: string
    sender: 'eliza' | 'user'
}

@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.css'],
})
export class AppComponent {
    title = 'Eliza'
    statement: string = '';
    responses: Response[] = [
        {
            text: 'What is your name?',
            sender: 'eliza',
        },
    ];
    introFinished: boolean = false;

    constructor(
        @Inject(ElizaService)
        private client: ObservableClient<typeof ElizaService>
    ) {}

    onSend(event?: MouseEvent) {
        if (event) { event.stopPropagation(); }
        this.responses = [...this.responses, { text: this.statement, sender: 'user' }]
        if (this.introFinished) {
            this.client.say({ sentence: this.statement }).subscribe((next) => {
                this.responses = [...this.responses, {text: next.sentence, sender: 'eliza'}]
            })
        } else {
            this.client.introduce({name: this.statement}).subscribe(
                (next) => {
                    this.responses = [...this.responses, {text: next.sentence, sender: 'eliza'}]
                }, 
                (err) => console.log(err), 
                () => {
                    this.introFinished = true;
                }
            );
        }
        this.statement = '';
    }
}

// react/vite/src/App.tsx
import {
    createPromiseClient,
    createConnectTransport,
} from '@bufbuild/connect-web-next'
import { connectCodeFromHttpStatus} from '@bufbuild/connect-core/protocol-connect';
import { grpcWebCodeFromHttpStatus} from '@bufbuild/connect-core/protocol-grpc';
import React, { useState } from 'react'
import './App.css'
import { ElizaService } from './gen/buf/connect/demo/eliza/v1/eliza_connectweb.js'
import { IntroduceRequest } from './gen/buf/connect/demo/eliza/v1/eliza_pb.js'

console.log(connectCodeFromHttpStatus(431));
console.log(grpcWebCodeFromHttpStatus(200));

interface Response {
    text: string
    sender: 'eliza' | 'user'
}

function App() {
    const [statement, setStatement] = useState<string>('')
    const [introFinished, setIntroFinished] = useState<boolean>(false)
    const [responses, setResponses] = useState<Response[]>([
        {
            text: 'What is your name?',
            sender: 'eliza',
        },
    ])

    // Make the Eliza Service client
    const client = createPromiseClient(
        ElizaService,
        createConnectTransport({
            baseUrl: 'https://demo.connect.build',
        })
    )

    const send = async (sentence: string) => {
        setResponses((resp) => [...resp, { text: sentence, sender: 'user' }])
        setStatement('')

        if (introFinished) {
            const response = await client.say({
                sentence,
            })

            setResponses((resp) => [
                ...resp,
                { text: response.sentence, sender: 'eliza' },
            ])
        } else {
            const request = new IntroduceRequest({
                name: sentence,
            })

            for await (const response of client.introduce(request)) {
                setResponses((resp) => [
                    ...resp,
                    { text: response.sentence, sender: 'eliza' },
                ])
            }

            setIntroFinished(true)
        }
    }

    const handleStatementChange = (
        event: React.ChangeEvent<HTMLInputElement>
    ) => {
        setStatement(event.target.value)
    }

    const handleSend = () => {
        send(statement)
    }

    const handleKeyPress = (event: any) => {
        if (event.key === 'Enter') {
            handleSend()
        }
    }

    return (
        <div>
            <header className="app-header">
                <h1>Eliza</h1>
            </header>
            <div className="container">
                {responses.map((resp, i) => {
                    return (
                        <div
                            key={`resp${i}`}
                            className={
                                resp.sender === 'eliza'
                                    ? 'eliza-resp-container'
                                    : 'user-resp-container'
                            }
                        >
                            <p className="resp-text">{resp.text}</p>
                        </div>
                    )
                })}
                <div>
                    <input
                        type="text"
                        className="text-input"
                        value={statement}
                        onChange={handleStatementChange}
                        onKeyPress={handleKeyPress}
                    />
                    <button onClick={handleSend}>Send</button>
                </div>
            </div>
        </div>
    )
}

export default App
